name: Build and Push Docker Image

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to GitHub Docker Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and tag Docker image
        run: |
          IMAGE_NAME=ghcr.io/RustyCZ/pblayla
          TAG=${{ github.ref_name }}
          docker build --file=./PbLayla/Dockerfile -t $IMAGE_NAME:$TAG .
          docker tag $IMAGE_NAME:$TAG $IMAGE_NAME:latest

      - name: Push Docker image
        run: |
          IMAGE_NAME=ghcr.io/RustyCZ/pblayla
          TAG=${{ github.ref_name }}
          docker push $IMAGE_NAME:$TAG
          docker push $IMAGE_NAME:latest
